#!/usr/bin/env bash

wallpapers_path="$HOME/Pictures/wallpaper"
pid=`pidof wpaperd | awk '{print $1}'`

echo old process $pid need be killed!!!
wpaperd

sleep 5

kill $pid
echo old process $pid was be killed!!!
